<?php
/**
 * STORYFOUNDRY web installer (cPanel friendly — no shell required).
 * Visit /install.php once, then delete it or leave it (it self-locks).
 */
define('SF_ROOT', __DIR__);
/* The installer is operator-facing and is meant to be deleted after use: show errors
   so a fatal reports itself instead of producing a blank page on the server. */
ini_set('display_errors', '1');
error_reporting(E_ALL);
require_once SF_ROOT . '/core/util.php';
require_once SF_ROOT . '/core/security.php';
if (php_sapi_name() !== 'cli') { sf_session_harden(); sf_security_headers(); }
session_start();
$step = isset($_GET['step']) ? (int) $_GET['step'] : 1;
$err = ''; $ok = '';

/* already installed? (steps 3 and 4 must still run — config.php exists by then) */
if (is_file(SF_ROOT . '/config.php') && empty($_GET['force']) && $step < 3) {
    $c = @require SF_ROOT . '/config.php';
    if (is_array($c)) {
        echo '<!doctype html><meta charset="utf-8"><div style="font:15px system-ui;max-width:640px;margin:80px auto;padding:28px;border:1px solid #e2e6ec;border-radius:14px">'
            . '<h2>STORYFOUNDRY is already installed</h2><p>config.php exists. To reinstall, delete <code>config.php</code> or open <code>install.php?force=1</code> (this wipes data).</p>'
            . '<p><a href="index.php" style="color:#c77700;font-weight:700">Go to the app →</a></p></div>';
        exit;
    }
}

/* ---------------- step 2: save DB config ---------------- */
if ($step === 2 && $_POST) {
    $host = trim(sf_post('host', 'localhost')); $name = trim(sf_post('name'));
    $user = trim(sf_post('user')); $pass = (string) sf_post('pass');
    $url  = rtrim(trim(sf_post('url')), '/') . '/';
    $token = bin2hex(function_exists('random_bytes') ? random_bytes(16) : str_shuffle(md5(microtime(true))));
    $appkey = bin2hex(function_exists('random_bytes') ? random_bytes(32) : str_shuffle(md5(microtime(true) . $token)));
    try {
        $pdo = new PDO('mysql:host=' . $host . ';charset=utf8mb4', $user, $pass, array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
        $pdo->exec('CREATE DATABASE IF NOT EXISTS `' . str_replace('`', '', $name) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
        $pdo->exec('USE `' . str_replace('`', '', $name) . '`');
        $cfg = "<?php\n/* STORYFOUNDRY configuration — generated by install.php */\nreturn array(\n"
            . "  'db' => array(\n    'host' => " . var_export($host, true) . ",\n    'name' => " . var_export($name, true) . ",\n"
            . "    'user' => " . var_export($user, true) . ",\n    'pass' => " . var_export($pass, true) . ",\n    'charset' => 'utf8mb4',\n  ),\n"
            . "  'app' => array(\n    'url' => " . var_export($url, true) . ",\n    'name' => 'STORYFOUNDRY',\n    'tagline' => 'From Idea to Finished Story.',\n"
            . "    'env' => 'production',\n    'debug' => false,\n    'timezone' => 'Africa/Lagos',\n"
            . "    'cron_token' => " . var_export($token, true) . ", 'key' => " . var_export($appkey, true) . ",\n    'queue_inline_seconds' => 20,\n    'mock_fallback_allowed' => true,\n  ),\n"
            . "  'security' => array('csrf' => true, 'rate_limit' => true, 'min_pass' => 8, 'login_max_attempts' => 8, 'login_window' => 900),\n"
            . "  'uploads' => array('max_mb' => 64, 'allowed' => 'jpg,jpeg,png,webp,gif,mp3,wav,m4a,mp4,mov,webm,srt,vtt,pdf,zip,json,svg'),\n);\n";
        if (!is_writable(SF_ROOT)) { $err = SF_ROOT . ' is not writable — set folder permissions to 0755 in cPanel File Manager.'; }
        elseif (@file_put_contents(SF_ROOT . '/config.php', $cfg) === false) { $err = 'Could not write config.php (permissions).'; }
        else { header('Location: install.php?step=3'); exit; }
    } catch (Exception $e) {
        $err = 'Database connection failed: ' . e($e->getMessage());
    }
}

/* ---------------- step 3: migrate + seed ---------------- */
if ($step === 3 && $_POST) {
    require_once SF_ROOT . '/core/bootstrap.php';
    require_once SF_ROOT . '/core/schema.php';
    /* idempotent migration: add columns introduced after the first release */
    try {
        $cols = db_all('SHOW COLUMNS FROM projects');
        $have = array(); foreach ($cols as $c) { $have[] = $c['Field']; }
        if (!in_array('client_id', $have, true)) { db_exec('ALTER TABLE projects ADD COLUMN client_id INT UNSIGNED DEFAULT NULL AFTER agency_id'); }
    } catch (Exception $e) { /* non-fatal */ }
    try {
        $t = sf_schema();
        if (isset($t['brand_kits'])) { db()->exec($t['brand_kits']); }   /* idempotent: CREATE TABLE IF NOT EXISTS */
    } catch (Exception $e) { /* non-fatal */ }
    try {
        foreach (sf_schema() as $name => $sql) { db()->exec($sql); }

        /* plans */
        db()->exec("DELETE FROM plans");
        db_exec("INSERT INTO plans (pkey,name,price,credits,features,limits,sort,active) VALUES
          ('free','Free',0,150,'Idea Engine|Story Generator|Scene Engine|480p export|1 project','{\"projects\":1,\"storage_mb\":200}',1,1),
          ('pro','Pro',24500,1500,'Everything in Free|AI Director & Shot List|Voice + Music Studio|1080p export|10 projects|Brand Kit','{\"projects\":10,\"storage_mb\":5120}',2,1),
          ('studio','Studio',78000,6000,'Everything in Pro|Video Generation|Content Factory|Series Builder|4K export|Priority queue','{\"projects\":50,\"storage_mb\":51200}',3,1),
          ('agency','Agency',220000,20000,'Everything in Studio|Agency Workspace|Client Portal|12 seats|Shared assets','{\"projects\":500,\"storage_mb\":204800,\"seats\":12}',4,1)");

        /* feature flags */
        db()->exec("DELETE FROM feature_flags");
        foreach (sf_features() as $f) {
            db_exec('INSERT INTO feature_flags (fkey,name,enabled,min_plan,credit_cost,daily_limit,maintenance) VALUES (?,?,?,?,?,?,?)',
                array($f[0], $f[1], 1, $f[3], $f[2], $f[4], 0));
        }

        /* settings */
        $defaults = array(
            'credits_new_user' => 150, 'credits_referral' => 250, 'credits_rewarded_ad' => 25,
            'referral_enabled' => 1, 'coupons_enabled' => 1, 'ads_enabled' => 1, 'rewarded_ads_enabled' => 1,
            'marketplace_commission' => 15, 'maintenance_mode' => 0, 'signup_open' => 1,
            'default_culture' => 'Yoruba', 'default_style' => 'cinematic', 'brand_name' => 'STORYFOUNDRY',
            'paystack_enabled' => 0, 'flutterwave_enabled' => 0, 'paystack_public' => '', 'paystack_secret' => '',
            'flutterwave_public' => '', 'flutterwave_secret' => '', 'currency' => 'NGN',
        );
        foreach ($defaults as $k => $v) { db_exec('INSERT IGNORE INTO settings (k,v) VALUES (?,?)', array($k, json_encode($v))); }

        /* admin user */
        $email = strtolower(trim(sf_post('admin_email'))); $pass = (string) sf_post('admin_pass');
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) { $err = 'Enter a valid admin email.'; }
        elseif (strlen($pass) < 8) { $err = 'Admin password must be at least 8 characters.'; }
        else {
            $hash = password_hash($pass, PASSWORD_BCRYPT, array('cost' => 11));
            db_exec("DELETE FROM users WHERE email=?", array($email));
            db_insert("INSERT INTO users (name,email,username,pass_hash,role,plan,credits,referral_code,email_verified,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                array('Platform Admin', $email, 'admin', $hash, 'super_admin', 'agency', 5000, 'SF-ADMIN', 1, 'active', db_now()));

            /* install + enable bundled addons */
            require_once SF_ROOT . '/core/plugins.php';
            $order = array('idea-engine','story-studio','character-studio','scene-engine','ai-director','image-studio',
                'voice-studio','audio-studio','video-engine','timeline-editor','subtitle-studio','thumbnail-studio',
                'social-suite','export-suite','asset-library','content-factory','media-pipeline','billing-suite',
                'subscriptions','paystack','flutterwave','ads-suite','notifications','analytics-pro','audit-security',
                'queue-manager','culture-pack','agency-workspace','marketplace','social-publishing','brand-kit','pwa-pack',
                /* provider adapters: installed disabled-by-config, enable in Admin → AI Providers */
                'openai','stability','elevenlabs','replicate','runway','openai-compatible');
            $i = 0;
            foreach ($order as $k) {
                if (!is_dir(SF_ROOT . '/plugins/' . $k)) continue;
                db_exec('INSERT IGNORE INTO plugins (pkey,name,version,enabled,config,installed_at) VALUES (?,?,?,?,?,?)',
                    array($k, $k, '1.0.0', 0, '{}', db_now()));
                $r = plugin_install($k);
                if (empty($r['ok'])) {
                    /* surface it: a silently disabled addon looks like a missing feature */
                    sf_log('warn', 'install', 'addon "' . $k . '" failed to install: ' . (isset($r['error']) ? $r['error'] : 'unknown error'));
                }
                $i++;
            }
            /* core providers get synced into DB */
            providers_bootstrap(); providers_sync_db();

            /* welcome content */
            db_exec("INSERT INTO announcements (type,title,body,target,created_at) VALUES (?,?,?,?,?)", array(
                'Feature', 'Welcome to STORYFOUNDRY',
                'Start at Idea → Story → Characters → Scenes → Shots → Images → Voice → Music → Video → Subtitles → Thumbnail → Social → Export. Add API keys in Admin → AI Providers to switch MOCK providers to REAL.',
                'all', db_now()));
            @file_put_contents(SF_ROOT . '/storage/logs/app-' . date('Y-m-d') . '.log', date('c') . "\tINFO\tinstall\tcompleted\n", FILE_APPEND);
            header('Location: install.php?step=4'); exit;
        }
    } catch (Exception $e) {
        $err = 'Migration failed: ' . e($e->getMessage());
    }
}
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Install STORYFOUNDRY</title>
<style>
body{font:15px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:#0b0c0e;color:#e8eaee;margin:0}
.wrap{max-width:720px;margin:40px auto;padding:0 20px}
.card{background:#14171c;border:1px solid #242a33;border-radius:14px;padding:24px;margin-bottom:16px}
h1{font-size:24px;margin:0 0 6px;letter-spacing:-.02em} h2{font-size:18px;margin:0 0 12px}
a{color:#ffb020} code{background:#191d24;padding:2px 6px;border-radius:5px;font-size:13px}
input,select{width:100%;padding:10px 12px;background:#0b0c0e;border:1px solid #242a33;color:#e8eaee;border-radius:9px;margin:6px 0 12px;box-sizing:border-box}
label{font-size:12px;font-weight:700;color:#a2acba;text-transform:uppercase;letter-spacing:.05em}
button{background:linear-gradient(180deg,#ffb020,#ff7a1a);color:#1a1206;border:0;padding:11px 20px;border-radius:10px;font-weight:800;cursor:pointer}
.err{background:#261315;border:1px solid #4a2026;color:#f2545b;padding:11px 14px;border-radius:10px;margin-bottom:14px}
.ok-chip{display:inline-block;padding:3px 9px;border-radius:99px;font-size:12px;font-weight:800;background:#0f2620;color:#33c98a;border:1px solid #1d4a37;margin-right:6px}
.bad-chip{display:inline-block;padding:3px 9px;border-radius:99px;font-size:12px;font-weight:800;background:#261315;color:#f2545b;border:1px solid #4a2026;margin-right:6px}
table{width:100%;border-collapse:collapse} td{padding:7px 0;border-bottom:1px solid #242a33}
small{color:#6d7889}
</style></head><body><div class="wrap">
<div class="card"><h1>STORYFOUNDRY installer</h1><p style="color:#a2acba;margin:0">From Idea to Finished Story — PHP + MySQL, cPanel ready.</p></div>

<?php if ($err): ?><div class="err"><?php echo $err; ?></div><?php endif; ?>

<?php if ($step === 1):
  $checks = array(
    'PHP 7.4+' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO MySQL' => extension_loaded('pdo_mysql'),
    'JSON' => extension_loaded('json'),
    'mbstring' => extension_loaded('mbstring'),
    'cURL (for AI APIs)' => function_exists('curl_init'),
    'GD (image thumbnails)' => function_exists('imagecreatetruecolor'),
    'FFmpeg (rendering)' => (function_exists('exec') && @exec('ffmpeg -version 2>&1') !== ''),
  );
  $writable = array('root' => is_writable(SF_ROOT), 'uploads' => is_writable(SF_ROOT . '/uploads'), 'storage' => is_writable(SF_ROOT . '/storage'));
?>
<div class="card"><h2>Step 1 — Requirements</h2>
<table><?php foreach ($checks as $k => $v): ?>
<tr><td><?php echo e($k); ?></td><td style="text-align:right"><?php echo $v ? '<span class="ok-chip">OK</span>' : '<span class="bad-chip">missing</span>'; ?></td></tr>
<?php endforeach; ?></table>
<p><small>Only <b>PDO MySQL</b> and a writable <b>root folder</b> are required. Everything else degrades gracefully and is labelled NOT CONFIGURED.</small></p>
<table><?php foreach ($writable as $k => $v): ?>
<tr><td>writable: /<?php echo e($k); ?></td><td style="text-align:right"><?php echo $v ? '<span class="ok-chip">yes</span>' : '<span class="bad-chip">no — chmod 0755</span>'; ?></td></tr>
<?php endforeach; ?></table>
<form method="post" action="?step=1"><button type="submit" onclick="window.location='?step=2';return false;">Continue →</button></form>
</div>
<?php endif; ?>

<?php if ($step === 2): ?>
<div class="card"><h2>Step 2 — Database</h2>
<p><small>In cPanel: MySQL® Databases → create a database and a user, add the user to the database with <b>ALL PRIVILEGES</b>. Names are usually prefixed with your cPanel username (e.g. <code>myuser_story</code>).</small></p>
<form method="post" action="?step=2">
<label>Host</label><input name="host" value="localhost" required>
<label>Database name</label><input name="name" placeholder="myuser_storyfoundry" required>
<label>Database user</label><input name="user" placeholder="myuser_sf" required>
<label>Database password</label><input name="pass" type="password" required>
<label>Site URL (with trailing slash)</label><input name="url" placeholder="https://www.storyfoundry.online/" required>
<button type="submit">Test &amp; save config →</button></form></div>
<?php endif; ?>

<?php if ($step === 3): ?>
<div class="card"><h2>Step 3 — Create tables &amp; admin</h2>
<form method="post" action="?step=3">
<label>Admin email</label><input name="admin_email" type="email" required>
<label>Admin password (min 8 chars)</label><input name="admin_pass" type="password" required minlength="8">
<button type="submit">Install →</button></form>
<p><small>This creates 37 tables, seeds plans, feature flags and settings, installs all bundled addons, and creates your admin account.</small></p></div>
<?php endif; ?>

<?php if ($step === 4): ?>
<div class="card"><h2>✅ Installed</h2>
<p>STORYFOUNDRY is ready.</p>
<ul>
<li><b>Delete install.php</b> now (or it stays locked until you pass <code>?force=1</code>).</li>
<li>Add a cron job in cPanel (Advanced → Cron Jobs) every 5 minutes:<br>
<code>*/5 * * * * /usr/local/bin/php -q <?php echo e(SF_ROOT); ?>/cron.php token=YOUR_TOKEN</code><br>
Your token is in <code>config.php</code> under <code>app.cron_token</code>.</li>
<li>Then open Admin → AI Providers and paste API keys to move providers from MOCK to REAL.</li>
</ul>
<?php
$warns = array();
try { $warns = db_all("SELECT message FROM logs WHERE src='install' AND level='warn' ORDER BY id DESC LIMIT 20"); } catch (Exception $e) {}
if ($warns): ?>
<div class="banner warn" style="margin-top:12px"><span>⚠</span><div><b>Some addons did not install.</b>
Enable them later in Admin → Addons, or check <?php echo e(SF_ROOT); ?>/storage/logs.
<ul style="margin:6px 0 0 18px"><?php foreach ($warns as $w): ?><li><?php echo e($w['message']); ?></li><?php endforeach; ?></ul></div></div>
<?php endif; ?>
<p><a href="index.php" style="font-weight:800">Open STORYFOUNDRY →</a></p></div>
<?php endif; ?>
</div></body></html>
