<?php
if (!defined('SF_ROOT')) { http_response_code(403); exit('Direct access denied'); }
/** Culture & language library (feature 80). Shapes texture, never stereotypes. */
function cultures() {
    static $c = null;
    if ($c !== null) return $c;
    $c = array(
        'Yoruba' => array('region' => 'South-West Nigeria', 'city' => 'Ibadan',
            'names' => array('Adunni', 'Tunde', 'Folake', 'Segun', 'Bimpe', 'Dapo', 'Yewande', 'Kunle'),
            'places' => array('Lagos Island', 'Ibadan', 'Abeokuta', 'Oyo', 'Ondo'),
            'flora' => array('flame trees', 'bougainvillea'), 'food' => array('amala', 'ewedu', 'akara', 'moin moin'),
            'greet' => 'E ku abo', 'texture' => 'aso-oke, courtyard compounds, market drums'),
        'Igbo' => array('region' => 'South-East Nigeria', 'city' => 'Enugu',
            'names' => array('Chidi', 'Adaeze', 'Ngozi', 'Emeka', 'Amara', 'Ikenna', 'Chioma', 'Obinna'),
            'places' => array('Enugu', 'Onitsha', 'Owerri', 'Aba', 'Nsukka'),
            'flora' => array('oil-bean trees', 'palm groves'), 'food' => array('abacha', 'nkwobi', 'ofe nsala'),
            'greet' => 'Nnoo', 'texture' => 'uli motifs, kola nut rites, red-capped chiefs'),
        'Hausa' => array('region' => 'Northern Nigeria', 'city' => 'Kano',
            'names' => array('Amina', 'Musa', 'Zainab', 'Ibrahim', 'Hauwa', 'Yusuf', 'Fatima', 'Bashir'),
            'places' => array('Kano', 'Kaduna', 'Sokoto', 'Maiduguri', 'Zaria'),
            'flora' => array('baobab', 'acacia', 'date palms'), 'food' => array('tuwo shinkafa', 'miyan kuka', 'suya'),
            'greet' => 'Sannu', 'texture' => 'mud-brick architecture, durbar horns, indigo dye pits'),
        'Nigerian Pidgin' => array('region' => 'Nigeria (urban)', 'city' => 'Lagos',
            'names' => array('Sade', 'Bayo', 'Tega', 'Nkechi', 'Femi', 'Aisha', 'Tobi', 'Rita'),
            'places' => array('Yaba', 'Ajegunle', 'Obalende', 'Wuse', 'Bodija'),
            'flora' => array('neem trees'), 'food' => array('bole', 'pepper soup', 'sharwama'),
            'greet' => 'How far', 'texture' => 'danfo buses, street hawkers, generator hum'),
        'Nigerian Urban' => array('region' => 'Nigeria', 'city' => 'Lagos',
            'names' => array('Temi', 'Ebuka', 'Zara', 'Ife', 'Kelvin', 'Simi', 'Dami', 'Uche'),
            'places' => array('Victoria Island', 'Lekki', 'Ikoyi', 'Garki', 'GRA'),
            'flora' => array('palm-lined boulevards'), 'food' => array('jollof rice', 'asun', 'small chops'),
            'greet' => 'Good afternoon', 'texture' => 'glass towers, Third Mainland traffic, co-working hum'),
        'Nigerian Traditional' => array('region' => 'Nigeria', 'city' => 'a riverside town',
            'names' => array('Ade', 'Nneka', 'Oluwa', 'Ifedayo', 'Uduak', 'Chinaza'),
            'places' => array('the village square', 'the shrine grove', 'the old compound'),
            'flora' => array('iyan trees', 'sacred groves'), 'food' => array('pounded yam', 'palm wine'),
            'greet' => 'Ku abo', 'texture' => 'masquerade drums, chalk markings, elder council'),
        'African' => array('region' => 'Pan-African', 'city' => 'a coastal capital',
            'names' => array('Zuri', 'Kwame', 'Ayana', 'Sipho', 'Nia', 'Kofi', 'Lerato', 'Bakari'),
            'places' => array('a highland valley', 'the delta', 'a savanna town'),
            'flora' => array('acacia', 'baobab', 'frangipani'), 'food' => array('jollof', 'groundnut stew', 'injera'),
            'greet' => 'Welcome', 'texture' => 'kente and ankara, talking drums, wide skies'),
        'Ghanaian' => array('region' => 'Ghana', 'city' => 'Accra',
            'names' => array('Ama', 'Kwesi', 'Akosua', 'Yaw', 'Efua', 'Kofi', 'Adjoa', 'Nana'),
            'places' => array('Accra', 'Kumasi', 'Cape Coast', 'Tamale'),
            'flora' => array('cocoa groves', 'palms'), 'food' => array('fufu', 'banku', 'waakye', 'kelewele'),
            'greet' => 'Akwaaba', 'texture' => 'kente cloth, highlife horns, Atlantic forts'),
        'Kenyan' => array('region' => 'Kenya', 'city' => 'Nairobi',
            'names' => array('Amani', 'Wanjiru', 'Otieno', 'Njeri', 'Kamau', 'Zawadi', 'Baraka', 'Achieng'),
            'places' => array('Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'),
            'flora' => array('jacaranda', 'acacia'), 'food' => array('ugali', 'nyama choma', 'chapati'),
            'greet' => 'Jambo', 'texture' => 'matatus, Rift Valley light, coastal dhows'),
        'South African' => array('region' => 'South Africa', 'city' => 'Johannesburg',
            'names' => array('Thandi', 'Sipho', 'Lerato', 'Mandla', 'Naledi', 'Bongani', 'Zanele', 'Kagiso'),
            'places' => array('Johannesburg', 'Cape Town', 'Durban', 'Soweto'),
            'flora' => array('protea', 'fynbos'), 'food' => array('braai', 'bunny chow', 'pap'),
            'greet' => 'Sawubona', 'texture' => 'Table Mountain, kwaito bass, township murals'),
        'American' => array('region' => 'United States', 'city' => 'the city',
            'names' => array('Maya', 'Dylan', 'Jordan', 'Ava', 'Marcus', 'Chloe', 'Ethan', 'Zoe'),
            'places' => array('Brooklyn', 'Austin', 'Seattle', 'Miami', 'Chicago'),
            'flora' => array('maple', 'spruce'), 'food' => array('diner coffee', 'barbecue', 'bagels'),
            'greet' => 'Hey', 'texture' => 'neon signage, freeway hum, corner delis'),
        'British' => array('region' => 'United Kingdom', 'city' => 'a northern town',
            'names' => array('Ellie', 'Oliver', 'Priya', 'Callum', 'Freya', 'Idris', 'Niamh', 'Tariq'),
            'places' => array('Manchester', 'Bristol', 'Glasgow', 'Hackney', 'Brighton'),
            'flora' => array('plane trees', 'bluebells'), 'food' => array('a full English', 'curry chips', 'sticky toffee pudding'),
            'greet' => 'Alright?', 'texture' => 'brick terraces, drizzle, corner pubs'),
        'Indian' => array('region' => 'India', 'city' => 'a coastal city',
            'names' => array('Ananya', 'Rohan', 'Meera', 'Kabir', 'Ishita', 'Arjun', 'Nisha', 'Dev'),
            'places' => array('Mumbai', 'Delhi', 'Kochi', 'Kolkata', 'Jaipur'),
            'flora' => array('banyan', 'marigold'), 'food' => array('chai', 'biryani', 'pani puri'),
            'greet' => 'Namaste', 'texture' => 'monsoon light, rangoli, temple bells'),
        'Chinese' => array('region' => 'China', 'city' => 'a river city',
            'names' => array('Mei', 'Wei', 'Ling', 'Jian', 'Xiu', 'Hao', 'Yun', 'Bo'),
            'places' => array('Shanghai', 'Chengdu', "Xi'an", 'Guangzhou'),
            'flora' => array('bamboo', 'plum blossom'), 'food' => array('dumplings', 'noodles', 'tea'),
            'greet' => 'Ni hao', 'texture' => 'lanterns, high-speed rail, mist peaks'),
        'Korean' => array('region' => 'Korea', 'city' => 'Seoul',
            'names' => array('Min-ji', 'Ji-hoon', 'Seo-yeon', 'Hyun-woo', 'Soo-ah', 'Tae-yang'),
            'places' => array('Seoul', 'Busan', 'Jeonju', 'Incheon'),
            'flora' => array('cherry blossom', 'pine'), 'food' => array('kimchi', 'tteokbokki', 'ramyeon'),
            'greet' => 'Annyeong', 'texture' => 'neon alleys, hanbok, mountain temples'),
        'Japanese' => array('region' => 'Japan', 'city' => 'a port town',
            'names' => array('Hana', 'Ren', 'Yuki', 'Haruto', 'Sakura', 'Kenji', 'Aoi'),
            'places' => array('Kyoto', 'Tokyo', 'Osaka', 'Nara', 'Sapporo'),
            'flora' => array('cherry blossom', 'maple', 'bamboo'), 'food' => array('ramen', 'onigiri', 'matcha'),
            'greet' => 'Konnichiwa', 'texture' => 'paper lanterns, rain on tile, quiet trains'),
        'Turkish' => array('region' => 'Turkiye', 'city' => 'a Bosphorus town',
            'names' => array('Elif', 'Emre', 'Zeynep', 'Mert', 'Ayse', 'Kaan'),
            'places' => array('Istanbul', 'Izmir', 'Cappadocia', 'Antalya'),
            'flora' => array('cypress', 'tulip'), 'food' => array('simit', 'kebap', 'baklava'),
            'greet' => 'Merhaba', 'texture' => 'call to prayer, tea gardens, tiled courtyards'),
        'Spanish' => array('region' => 'Spain / Hispanic', 'city' => 'a plaza town',
            'names' => array('Lucia', 'Mateo', 'Sofia', 'Hugo', 'Valeria', 'Pablo'),
            'places' => array('Sevilla', 'Barcelona', 'Valencia', 'Madrid'),
            'flora' => array('olive groves', 'bougainvillea'), 'food' => array('paella', 'tapas', 'churros'),
            'greet' => 'Hola', 'texture' => 'guitar, tiled patios, late dinners'),
        'French' => array('region' => 'France / Francophone', 'city' => 'a riverside quarter',
            'names' => array('Camille', 'Louis', 'Manon', 'Etienne', 'Ines', 'Noah'),
            'places' => array('Paris', 'Lyon', 'Marseille', 'Bordeaux'),
            'flora' => array('lime trees', 'lavender'), 'food' => array('croissant', 'coq au vin', 'tarte tatin'),
            'greet' => 'Bonjour', 'texture' => 'iron balconies, cafe terraces, accordion'),
        'Brazilian' => array('region' => 'Brazil', 'city' => 'a hillside city',
            'names' => array('Ana', 'Pedro', 'Larissa', 'Thiago', 'Beatriz', 'Rafa'),
            'places' => array('Rio', 'Sao Paulo', 'Salvador', 'Recife'),
            'flora' => array('ipe', 'jacaranda'), 'food' => array('feijoada', 'pao de queijo', 'acai'),
            'greet' => 'Oi', 'texture' => 'samba drums, Atlantic surf, tiled steps'),
    );
    $c = apply_filters('cultures.list', $c);
    return $c;
}
function culture_keys() { return array_keys(cultures()); }
function culture_get($k) { $c = cultures(); return isset($c[$k]) ? $c[$k] : $c['African']; }
function culture_context($k) {
    $c = culture_get($k);
    return array(
        'culture' => $k, 'region' => $c['region'], 'city' => $c['city'],
        'name'  => $c['names'][array_rand($c['names'])],
        'name2' => $c['names'][array_rand($c['names'])],
        'place' => $c['places'][array_rand($c['places'])],
        'flora' => $c['flora'][array_rand($c['flora'])],
        'food'  => $c['food'][array_rand($c['food'])],
        'greet' => $c['greet'], 'texture' => $c['texture'],
    );
}
function sf_pick($arr) { return $arr[array_rand($arr)]; }
