<div style="max-width:760px;margin:0 auto;padding:20px">
  <div class="row" style="gap:10px;margin-bottom:20px"><div class="logo">SF</div><b>STORYFOUNDRY</b><span class="spacer"></span><a class="btn sm" href="<?php echo e(sf_url(auth_check() ? 'index.php?r=dashboard' : 'index.php?r=home')); ?>">Back</a></div>
  <div class="card prose">
  <?php
  $p = isset($p) ? $p : 'terms';
  if ($p === 'privacy'): ?>
    <h2>Privacy Policy</h2>
    <p>We store account data, project content, generated assets, usage records and audit logs. Payments are verified server-side; card details are never stored by us.</p>
    <p>You may export or request deletion of your data at any time from Settings → Data.</p>
  <?php elseif ($p === 'about'): ?>
    <h2>About STORYFOUNDRY</h2>
    <p><b>STORYFOUNDRY</b> is an AI content production studio: one place to take an idea through story, characters,
    scenes, shots, images, voice, music, sound, video, subtitles, thumbnails and social distribution — then export it.</p>
    <p>The platform is built as a <b>core plus addons</b>: every production stage is an installable addon, so studios can be
    added, disabled or replaced without touching the core. It runs on ordinary PHP + MySQL hosting (cPanel friendly).</p>
    <p><b>Honesty policy.</b> Providers report one of four states: <span class="chip chip-ok">REAL</span>
    <span class="chip chip-mock">MOCK</span> <span class="chip chip-nc">NOT CONFIGURED</span>
    <span class="chip chip-off">DISABLED</span>. Nothing silently pretends to be real.</p>
  <?php elseif ($p === 'faq'): ?>
    <h2>Frequently asked questions</h2>
    <p><b>What is a credit?</b> One credit is the unit consumed by a generation. The flow is
    check → reserve → execute → consume on success, and the reservation is released if the job fails.</p>
    <p><b>Can I withdraw wallet funds?</b> No. Wallet funds can only be spent inside STORYFOUNDRY.</p>
    <p><b>Are all AI providers live?</b> Only those you configure with your own keys. Unconfigured providers show
    NOT CONFIGURED and are never used; development mocks are separate and labelled MOCK, and production never falls back to them silently.</p>
    <p><b>Do I need FFmpeg?</b> Only for real media rendering. If the host has no FFmpeg, renders fail with an explicit
    error instead of producing a fake file.</p>
    <p><b>Can I clone a real actor's voice or likeness?</b> No. Cloning real people, actors or copyrighted material is prohibited.</p>
    <p><b>Where is my data?</b> In your own database and uploads directory on your own host. Nothing is sent anywhere except
    to the AI providers you enable.</p>
  <?php elseif ($p === 'cookies'): ?>
    <h2>Cookie & privacy controls</h2>
    <p>STORYFOUNDRY sets one essential cookie — the session cookie — to keep you signed in. It contains no personal data
    beyond a random token and expires with the session.</p>
    <p>Preferences such as theme and language are stored per-account in your profile, not in tracking cookies. There is no
    third-party advertising tracker in the application.</p>
    <p>You may export or delete your data at any time from <a href="<?php echo e(sf_url('index.php?r=account&tab=data')); ?>">Settings → Data</a>.</p>
  <?php elseif ($p === 'contact'): ?>
    <h2>Contact</h2><p><b>Support</b> · support@storyfoundry.online</p><p><b>Business</b> · hello@storyfoundry.online</p><p><b>Abuse / DMCA</b> · legal@storyfoundry.online</p><p>Lagos, Nigeria.</p>
  <?php else: ?>
    <h2>Terms of Service</h2>
    <p><b>1. Service.</b> STORYFOUNDRY provides AI-assisted content production tooling. Output is generated by third-party or local models and may be inaccurate.</p>
    <p><b>2. Credits.</b> Credit flow is check → reserve → execute → consume. Failed generations release the reservation. Credits have no cash value.</p>
    <p><b>3. Wallet.</b> Wallet funds may only be spent inside STORYFOUNDRY. There is no withdrawal.</p>
    <p><b>4. Content.</b> You are responsible for content you generate. Unauthorized use of copyrighted material, or cloning of a real person's voice or likeness, is prohibited.</p>
    <p><b>5. Availability.</b> Features may be toggled, plan-gated or placed in maintenance without redeploying the application.</p>
  <?php endif; ?>
  </div>
</div>
